name: KT Stream Media
favicon: null
layout_spectrum: 0.91418
typography_spectrum: 0.1618316131643951
title: 'KT Stream Media: The Photography of Kaitlynn Reyell'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#afb5c0'
    - '#505052'
    - '#687179'
    - '#4e0b0c'
    - '#602e31'
  brandStrength: 0.9375
  lightness: 0.46974644460715353
  saturation: 0.606686039827764
  rhythmicContrast: 0.5
purpose: []
